#!/bin/sh

RED="\e[31m"
GREEN="\e[32m"
VIOLET="\e[35m"
ENDCOLOR="\e[0m"

clear
echo -e "${RED}Выберите радио:${GREEN}\n 1 - FreeCode\n 2 - Choco ${GREEN}\n 3 - Music\n 4 - Tiger_Dragon ${VIOLET}\n "
read -p "   ***********   " radio


if [ "$radio" = "1" ]
then 
    mpg123 https://coderadio-admin-v2.freecodecamp.org/listen/coderadio/radio.mp3
fi

if [ "$radio" = "2" ]
then
    mpg123 http://choco.hostingradio.ru:10010/fm
fi


if [ "$radio" = "3" ]
then
    mpg123 ~/music/*/*    
fi

if [ "$radio" = "4" ]
then
	mpg123 ~/music/*/*

else
    echo " Неправильно набран номер "
fi 

